from sqlalchemy.orm import Session
from models.path_model import Path
from models.power_model import Power
from models.province_model import Inland, Coast, Water


def generate_master_data(session: Session) -> None:
    powers = [
        Power(symbol="a", name="Austria", adjective="Austrian"),
        Power(symbol="e", name="England", adjective="English"),
        Power(symbol="f", name="France", adjective="French"),
        Power(symbol="g", name="Germany", adjective="German"),
        Power(symbol="i", name="Italy", adjective="Italian"),
        Power(symbol="r", name="Russia", adjective="Russian"),
        Power(symbol="t", name="Turkey", adjective="Turkish"),
    ]
    session.add_all(powers)
    session.commit()

    power_symbols = ["a", "e", "f", "g", "i", "r", "t"]
    powers = {symbol: session.query(Power).filter_by(symbol=symbol).first() for symbol in power_symbols}

    provinces = [
        Water(abbr="adr", name="Adriatic Water", jname="アドリア海"),
        Water(abbr="aeg", name="Aegean Water", jname="エーゲ海"),
        Coast(abbr="alb", name="Albania", jname="アルバニア"),
        Coast(abbr="ank", name="Ankara", jname="アンカラ", suppliable=True, region=powers["t"]),
        Coast(abbr="apu", name="Apulia", jname="アプリア", region=powers["i"]),
        Coast(abbr="arm", name="Armenia", jname="アルメニア", region=powers["t"]),
        Water(abbr="bal", name="Baltic Water", jname="バルト海"),
        Water(abbr="bar", name="Barents Water", jname="バレンツ海"),
        Coast(abbr="bel", name="Belgium", jname="ベルギー", suppliable=True),
        Coast(abbr="ber", name="Berlin", jname="ベルリン", suppliable=True, region=powers["g"]),
        Water(abbr="bla", name="Black Water", jname="黒海"),
        Inland(abbr="boh", name="Bohemia", jname="ボヘミア", region=powers["a"]),
        Water(abbr="bot", name="Gulf of Bothnia", jname="ボスニア湾"),
        Coast(abbr="bre", name="Brest", jname="ブレスト", suppliable=True, region=powers["f"]),
        Inland(abbr="bud", name="Budapest", jname="ブダペスト", suppliable=True, region=powers["a"]),
        Coast(abbr="bul", name="Bulgaria", jname="ブルガリア", suppliable=True),
        Coast(abbr="bul_ec", name="Bulgaria(EC)", jname="ブルガリア(EC)"),
        Coast(abbr="bul_sc", name="Bulgaria(SC)", jname="ブルガリア(SC)"),
        Inland(abbr="bur", name="Burgundy", jname="ブルゴーニュ", region=powers["f"]),
        Coast(abbr="cly", name="Clyde", jname="クライド", region=powers["e"]),
        Coast(abbr="con", name="Constantinople", jname="コンスタンティノープル", suppliable=True, region=powers["t"]),
        Coast(abbr="den", name="Denmark", jname="デンマーク", suppliable=True),
        Water(abbr="eas", name="Eastern Mediterranean", jname="東地中海"),
        Coast(abbr="edi", name="Edinburgh", jname="エディンバラ", suppliable=True, region=powers["e"]),
        Water(abbr="eng", name="English Channel", jname="イギリス海峡"),
        Coast(abbr="fin", name="Finland", jname="フィンランド", region=powers["r"]),
        Inland(abbr="gal", name="Galicia", jname="ガリツィア", region=powers["a"]),
        Coast(abbr="gas", name="Gascony", jname="ガスコーニュ", region=powers["f"]),
        Coast(abbr="gre", name="Greece", jname="ギリシア", suppliable=True),
        Water(abbr="hel", name="Helgoland Bight", jname="ヘルゴラント湾"),
        Coast(abbr="hol", name="Holland", jname="オランダ", suppliable=True),
        Water(abbr="ion", name="Ionian Water", jname="イオニア海"),
        Water(abbr="iri", name="Irish Water", jname="アイリッシュ海"),
        Coast(abbr="kie", name="Kiel", jname="キール", suppliable=True, region=powers["g"]),
        Coast(abbr="lon", name="London", jname="ロンドン", suppliable=True, region=powers["e"]),
        Coast(abbr="lvn", name="Livonia", jname="リヴォニア", region=powers["r"]),
        Coast(abbr="lvp", name="Liverpool", jname="リヴァプール", suppliable=True, region=powers["e"]),
        Water(abbr="lyo", name="Gulf of Lyon", jname="リオン湾"),
        Water(abbr="mao", name="Mid-Atlantic Ocean", jname="中大西洋"),
        Coast(abbr="mar", name="Marseilles", jname="マルセイユ", suppliable=True, region=powers["f"]),
        Inland(abbr="mos", name="Moscow", jname="モスクワ", suppliable=True, region=powers["r"]),
        Inland(abbr="mun", name="Munich", jname="ミュンヘン", suppliable=True, region=powers["g"]),
        Coast(abbr="naf", name="North Africa", jname="北アフリカ"),
        Water(abbr="nao", name="North Atlantic Ocean", jname="北大西洋"),
        Coast(abbr="nap", name="Naples", jname="ナポリ", suppliable=True, region=powers["i"]),
        Water(abbr="nth", name="North Water", jname="北海"),
        Water(abbr="nwg", name="Norwegian Water", jname="ノルウェー海"),
        Coast(abbr="nwy", name="Norway", jname="ノルウェー", suppliable=True),
        Inland(abbr="par", name="Paris", jname="パリ", suppliable=True, region=powers["f"]),
        Coast(abbr="pic", name="Picardy", jname="ピカルディ", region=powers["f"]),
        Coast(abbr="pie", name="Piedmont", jname="ピエモンテ", region=powers["i"]),
        Coast(abbr="por", name="Portugal", jname="ポルトガル", suppliable=True),
        Coast(abbr="pru", name="Prussia", jname="プロイセン", region=powers["g"]),
        Coast(abbr="rom", name="Rome", jname="ローマ", suppliable=True, region=powers["i"]),
        Inland(abbr="ruh", name="Ruhrl", jname="ルール", region=powers["g"]),
        Coast(abbr="rum", name="Rumania", jname="ルーマニア", suppliable=True),
        Inland(abbr="ser", name="Serbia", jname="セルビア", suppliable=True),
        Coast(abbr="sev", name="Sevastopol", jname="セヴァストポリ", suppliable=True, region=powers["r"]),
        Inland(abbr="sil", name="Silesia", jname="シレジア", region=powers["g"]),
        Water(abbr="ska", name="Skagerrak", jname="スカゲラク海峡"),
        Coast(abbr="smy", name="Smyrna", jname="スミルナ", suppliable=True, region=powers["t"]),
        Coast(abbr="spa", name="Spain", jname="スペイン", suppliable=True),
        Coast(abbr="spa_nc", name="Spain(NC)", jname="スペイン(NC)"),
        Coast(abbr="spa_sc", name="Spain(SC)", jname="スペイン(SC)"),
        Coast(abbr="stp", name="St. Petersburg", jname="サンクトペテルブルク", suppliable=True, region=powers["r"]),
        Coast(abbr="stp_nc", name="St. Petersburg(NC)", jname="サンクトペテルブルク(NC)"),
        Coast(abbr="stp_sc", name="St. Petersburg(SC)", jname="サンクトペテルブルク(SC)"),
        Coast(abbr="swe", name="Sweden", jname="スウェーデン", suppliable=True),
        Coast(abbr="syr", name="Syria", jname="シリア", region=powers["t"]),
        Coast(abbr="tri", name="Trieste", jname="トリエステ", suppliable=True, region=powers["a"]),
        Coast(abbr="tun", name="Tunis", jname="チュニス", suppliable=True),
        Coast(abbr="tus", name="Tuscany", jname="トスカーナ", region=powers["i"]),
        Inland(abbr="tyr", name="Tyrolia", jname="ティロル", region=powers["a"]),
        Water(abbr="tys", name="Tyrrhenian Water", jname="ティレニア海"),
        Inland(abbr="ukr", name="Ukraine", jname="ウクライナ", region=powers["r"]),
        Coast(abbr="ven", name="Venice", jname="ヴェネツィア", suppliable=True, region=powers["i"]),
        Inland(abbr="vie", name="Vienna", jname="ウィーン", suppliable=True, region=powers["a"]),
        Coast(abbr="wal", name="Wales", jname="ウェールズ", region=powers["e"]),
        Inland(abbr="war", name="Warsaw", jname="ワルシャワ", suppliable=True, region=powers["r"]),
        Water(abbr="wes", name="Western Mediterranean", jname="西地中海"),
        Coast(abbr="yor", name="Yorkshire", jname="ヨークシャー", region=powers["e"]),
    ]
    session.add_all(provinces)
    session.commit()

    paths = [
        Path(origin="adr", dest="apu", army=False, fleet=True),
        Path(origin="adr", dest="ion", army=False, fleet=True),
        Path(origin="adr", dest="alb", army=False, fleet=True),
        Path(origin="adr", dest="tri", army=False, fleet=True),
        Path(origin="adr", dest="ven", army=False, fleet=True),
        Path(origin="aeg", dest="gre", army=False, fleet=True),
        Path(origin="aeg", dest="smy", army=False, fleet=True),
        Path(origin="aeg", dest="bul", army=True, fleet=False),
        Path(origin="aeg", dest="bul_sc", army=False, fleet=True),
        Path(origin="aeg", dest="eas", army=False, fleet=True),
        Path(origin="aeg", dest="con", army=False, fleet=True),
        Path(origin="aeg", dest="ion", army=False, fleet=True),
        Path(origin="alb", dest="adr", army=False, fleet=True),
        Path(origin="alb", dest="gre", army=True, fleet=True),
        Path(origin="alb", dest="ser", army=True, fleet=False),
        Path(origin="alb", dest="ion", army=False, fleet=True),
        Path(origin="alb", dest="tri", army=True, fleet=True),
        Path(origin="ank", dest="smy", army=True, fleet=False),
        Path(origin="ank", dest="bla", army=False, fleet=True),
        Path(origin="ank", dest="arm", army=True, fleet=True),
        Path(origin="ank", dest="con", army=True, fleet=True),
        Path(origin="apu", dest="rom", army=True, fleet=False),
        Path(origin="apu", dest="ion", army=False, fleet=True),
        Path(origin="apu", dest="ven", army=True, fleet=True),
        Path(origin="apu", dest="adr", army=False, fleet=True),
        Path(origin="apu", dest="nap", army=True, fleet=True),
        Path(origin="arm", dest="bla", army=False, fleet=True),
        Path(origin="arm", dest="syr", army=True, fleet=False),
        Path(origin="arm", dest="ank", army=True, fleet=True),
        Path(origin="arm", dest="sev", army=True, fleet=True),
        Path(origin="arm", dest="smy", army=True, fleet=False),
        Path(origin="bal", dest="den", army=False, fleet=True),
        Path(origin="bal", dest="ber", army=False, fleet=True),
        Path(origin="bal", dest="kie", army=False, fleet=True),
        Path(origin="bal", dest="swe", army=False, fleet=True),
        Path(origin="bal", dest="lvn", army=False, fleet=True),
        Path(origin="bal", dest="bot", army=False, fleet=True),
        Path(origin="bal", dest="pru", army=False, fleet=True),
        Path(origin="bar", dest="nwy", army=False, fleet=True),
        Path(origin="bar", dest="nwg", army=False, fleet=True),
        Path(origin="bar", dest="stp", army=True, fleet=False),
        Path(origin="bar", dest="stp_nc", army=False, fleet=True),
        Path(origin="bel", dest="eng", army=False, fleet=True),
        Path(origin="bel", dest="pic", army=True, fleet=True),
        Path(origin="bel", dest="hol", army=True, fleet=True),
        Path(origin="bel", dest="ruh", army=True, fleet=False),
        Path(origin="bel", dest="nth", army=False, fleet=True),
        Path(origin="bel", dest="bur", army=True, fleet=False),
        Path(origin="ber", dest="bal", army=False, fleet=True),
        Path(origin="ber", dest="kie", army=True, fleet=True),
        Path(origin="ber", dest="mun", army=True, fleet=False),
        Path(origin="ber", dest="sil", army=True, fleet=False),
        Path(origin="ber", dest="pru", army=True, fleet=True),
        Path(origin="bla", dest="arm", army=False, fleet=True),
        Path(origin="bla", dest="con", army=False, fleet=True),
        Path(origin="bla", dest="ank", army=False, fleet=True),
        Path(origin="bla", dest="sev", army=False, fleet=True),
        Path(origin="bla", dest="rum", army=False, fleet=True),
        Path(origin="bla", dest="bul", army=True, fleet=False),
        Path(origin="bla", dest="bul_ec", army=False, fleet=True),
        Path(origin="boh", dest="mun", army=True, fleet=False),
        Path(origin="boh", dest="sil", army=True, fleet=False),
        Path(origin="boh", dest="gal", army=True, fleet=False),
        Path(origin="boh", dest="vie", army=True, fleet=False),
        Path(origin="boh", dest="tyr", army=True, fleet=False),
        Path(origin="bot", dest="swe", army=False, fleet=True),
        Path(origin="bot", dest="fin", army=False, fleet=True),
        Path(origin="bot", dest="lvn", army=False, fleet=True),
        Path(origin="bot", dest="stp", army=True, fleet=False),
        Path(origin="bot", dest="stp_sc", army=False, fleet=True),
        Path(origin="bot", dest="bal", army=False, fleet=True),
        Path(origin="bre", dest="mao", army=False, fleet=True),
        Path(origin="bre", dest="eng", army=False, fleet=True),
        Path(origin="bre", dest="par", army=True, fleet=False),
        Path(origin="bre", dest="pic", army=True, fleet=True),
        Path(origin="bre", dest="gas", army=True, fleet=True),
        Path(origin="bud", dest="tri", army=True, fleet=False),
        Path(origin="bud", dest="ser", army=True, fleet=False),
        Path(origin="bud", dest="gal", army=True, fleet=False),
        Path(origin="bud", dest="vie", army=True, fleet=False),
        Path(origin="bud", dest="rum", army=True, fleet=False),
        Path(origin="bul", dest="con", army=True, fleet=False),
        Path(origin="bul", dest="ser", army=True, fleet=False),
        Path(origin="bul", dest="gre", army=True, fleet=False),
        Path(origin="bul", dest="rum", army=True, fleet=False),
        Path(origin="bul", dest="aeg", army=False, fleet=True),
        Path(origin="bul", dest="bla", army=False, fleet=True),
        Path(origin="bul_ec", dest="con", army=False, fleet=True),
        Path(origin="bul_ec", dest="bla", army=False, fleet=True),
        Path(origin="bul_ec", dest="rum", army=False, fleet=True),
        Path(origin="bul_sc", dest="con", army=False, fleet=True),
        Path(origin="bul_sc", dest="aeg", army=False, fleet=True),
        Path(origin="bul_sc", dest="gre", army=False, fleet=True),
        Path(origin="bur", dest="par", army=True, fleet=False),
        Path(origin="bur", dest="pic", army=True, fleet=False),
        Path(origin="bur", dest="gas", army=True, fleet=False),
        Path(origin="bur", dest="ruh", army=True, fleet=False),
        Path(origin="bur", dest="bel", army=True, fleet=False),
        Path(origin="bur", dest="mar", army=True, fleet=False),
        Path(origin="bur", dest="mun", army=True, fleet=False),
        Path(origin="cly", dest="edi", army=True, fleet=True),
        Path(origin="cly", dest="nao", army=False, fleet=True),
        Path(origin="cly", dest="lvp", army=True, fleet=True),
        Path(origin="cly", dest="nwg", army=False, fleet=True),
        Path(origin="con", dest="aeg", army=False, fleet=True),
        Path(origin="con", dest="ank", army=True, fleet=True),
        Path(origin="con", dest="bla", army=False, fleet=True),
        Path(origin="con", dest="bul", army=True, fleet=False),
        Path(origin="con", dest="bul_sc", army=False, fleet=True),
        Path(origin="con", dest="bul_ec", army=False, fleet=True),
        Path(origin="con", dest="smy", army=True, fleet=True),
        Path(origin="den", dest="swe", army=True, fleet=True),
        Path(origin="den", dest="hel", army=False, fleet=True),
        Path(origin="den", dest="bal", army=False, fleet=True),
        Path(origin="den", dest="nth", army=False, fleet=True),
        Path(origin="den", dest="ska", army=False, fleet=True),
        Path(origin="den", dest="kie", army=True, fleet=True),
        Path(origin="eas", dest="syr", army=False, fleet=True),
        Path(origin="eas", dest="aeg", army=False, fleet=True),
        Path(origin="eas", dest="ion", army=False, fleet=True),
        Path(origin="eas", dest="smy", army=False, fleet=True),
        Path(origin="edi", dest="yor", army=True, fleet=True),
        Path(origin="edi", dest="nth", army=False, fleet=True),
        Path(origin="edi", dest="nwg", army=False, fleet=True),
        Path(origin="edi", dest="cly", army=True, fleet=True),
        Path(origin="edi", dest="lvp", army=True, fleet=False),
        Path(origin="eng", dest="mao", army=False, fleet=True),
        Path(origin="eng", dest="lon", army=False, fleet=True),
        Path(origin="eng", dest="nth", army=False, fleet=True),
        Path(origin="eng", dest="bel", army=False, fleet=True),
        Path(origin="eng", dest="pic", army=False, fleet=True),
        Path(origin="eng", dest="bre", army=False, fleet=True),
        Path(origin="eng", dest="iri", army=False, fleet=True),
        Path(origin="eng", dest="wal", army=False, fleet=True),
        Path(origin="fin", dest="bot", army=False, fleet=True),
        Path(origin="fin", dest="swe", army=True, fleet=True),
        Path(origin="fin", dest="nwy", army=True, fleet=False),
        Path(origin="fin", dest="stp_sc", army=False, fleet=True),
        Path(origin="fin", dest="stp", army=True, fleet=False),
        Path(origin="gal", dest="boh", army=True, fleet=False),
        Path(origin="gal", dest="sil", army=True, fleet=False),
        Path(origin="gal", dest="rum", army=True, fleet=False),
        Path(origin="gal", dest="ukr", army=True, fleet=False),
        Path(origin="gal", dest="war", army=True, fleet=False),
        Path(origin="gal", dest="vie", army=True, fleet=False),
        Path(origin="gal", dest="bud", army=True, fleet=False),
        Path(origin="gas", dest="mao", army=False, fleet=True),
        Path(origin="gas", dest="spa", army=True, fleet=False),
        Path(origin="gas", dest="spa_nc", army=False, fleet=True),
        Path(origin="gas", dest="bre", army=True, fleet=True),
        Path(origin="gas", dest="bur", army=True, fleet=False),
        Path(origin="gas", dest="mar", army=True, fleet=False),
        Path(origin="gas", dest="par", army=True, fleet=False),
        Path(origin="gre", dest="alb", army=True, fleet=True),
        Path(origin="gre", dest="ion", army=False, fleet=True),
        Path(origin="gre", dest="ser", army=True, fleet=False),
        Path(origin="gre", dest="aeg", army=False, fleet=True),
        Path(origin="gre", dest="bul", army=True, fleet=False),
        Path(origin="gre", dest="bul_sc", army=False, fleet=True),
        Path(origin="hel", dest="den", army=False, fleet=True),
        Path(origin="hel", dest="kie", army=False, fleet=True),
        Path(origin="hel", dest="nth", army=False, fleet=True),
        Path(origin="hel", dest="hol", army=False, fleet=True),
        Path(origin="hol", dest="hel", army=False, fleet=True),
        Path(origin="hol", dest="bel", army=True, fleet=True),
        Path(origin="hol", dest="nth", army=False, fleet=True),
        Path(origin="hol", dest="ruh", army=True, fleet=False),
        Path(origin="hol", dest="kie", army=True, fleet=True),
        Path(origin="ion", dest="nap", army=False, fleet=True),
        Path(origin="ion", dest="eas", army=False, fleet=True),
        Path(origin="ion", dest="gre", army=False, fleet=True),
        Path(origin="ion", dest="apu", army=False, fleet=True),
        Path(origin="ion", dest="alb", army=False, fleet=True),
        Path(origin="ion", dest="aeg", army=False, fleet=True),
        Path(origin="ion", dest="adr", army=False, fleet=True),
        Path(origin="ion", dest="tun", army=False, fleet=True),
        Path(origin="ion", dest="tys", army=False, fleet=True),
        Path(origin="iri", dest="mao", army=False, fleet=True),
        Path(origin="iri", dest="nao", army=False, fleet=True),
        Path(origin="iri", dest="lvp", army=False, fleet=True),
        Path(origin="iri", dest="eng", army=False, fleet=True),
        Path(origin="iri", dest="wal", army=False, fleet=True),
        Path(origin="kie", dest="ruh", army=True, fleet=False),
        Path(origin="kie", dest="hol", army=True, fleet=True),
        Path(origin="kie", dest="mun", army=True, fleet=False),
        Path(origin="kie", dest="hel", army=False, fleet=True),
        Path(origin="kie", dest="den", army=True, fleet=True),
        Path(origin="kie", dest="ber", army=True, fleet=True),
        Path(origin="kie", dest="bal", army=False, fleet=True),
        Path(origin="lon", dest="nth", army=False, fleet=True),
        Path(origin="lon", dest="eng", army=False, fleet=True),
        Path(origin="lon", dest="wal", army=True, fleet=True),
        Path(origin="lon", dest="yor", army=True, fleet=True),
        Path(origin="lvn", dest="bal", army=False, fleet=True),
        Path(origin="lvn", dest="stp", army=True, fleet=False),
        Path(origin="lvn", dest="stp_sc", army=False, fleet=True),
        Path(origin="lvn", dest="mos", army=True, fleet=False),
        Path(origin="lvn", dest="bot", army=False, fleet=True),
        Path(origin="lvn", dest="pru", army=True, fleet=True),
        Path(origin="lvn", dest="war", army=True, fleet=False),
        Path(origin="lvp", dest="yor", army=True, fleet=False),
        Path(origin="lvp", dest="cly", army=True, fleet=True),
        Path(origin="lvp", dest="wal", army=True, fleet=True),
        Path(origin="lvp", dest="nao", army=False, fleet=True),
        Path(origin="lvp", dest="iri", army=False, fleet=True),
        Path(origin="lvp", dest="edi", army=True, fleet=False),
        Path(origin="lyo", dest="mar", army=False, fleet=True),
        Path(origin="lyo", dest="spa", army=True, fleet=False),
        Path(origin="lyo", dest="spa_sc", army=False, fleet=True),
        Path(origin="lyo", dest="pie", army=False, fleet=True),
        Path(origin="lyo", dest="wes", army=False, fleet=True),
        Path(origin="lyo", dest="tys", army=False, fleet=True),
        Path(origin="lyo", dest="tus", army=False, fleet=True),
        Path(origin="mao", dest="spa", army=True, fleet=False),
        Path(origin="mao", dest="spa_nc", army=False, fleet=True),
        Path(origin="mao", dest="bre", army=False, fleet=True),
        Path(origin="mao", dest="por", army=False, fleet=True),
        Path(origin="mao", dest="gas", army=False, fleet=True),
        Path(origin="mao", dest="nao", army=False, fleet=True),
        Path(origin="mao", dest="naf", army=False, fleet=True),
        Path(origin="mao", dest="wes", army=False, fleet=True),
        Path(origin="mao", dest="eng", army=False, fleet=True),
        Path(origin="mao", dest="iri", army=False, fleet=True),
        Path(origin="mao", dest="spa_sc", army=False, fleet=True),
        Path(origin="mar", dest="spa", army=True, fleet=False),
        Path(origin="mar", dest="spa", army=True, fleet=False),
        Path(origin="mar", dest="pie", army=True, fleet=True),
        Path(origin="mar", dest="gas", army=True, fleet=False),
        Path(origin="mar", dest="spa_sc", army=False, fleet=True),
        Path(origin="mar", dest="bur", army=True, fleet=False),
        Path(origin="mar", dest="lyo", army=False, fleet=True),
        Path(origin="mos", dest="lvn", army=True, fleet=False),
        Path(origin="mos", dest="ukr", army=True, fleet=False),
        Path(origin="mos", dest="stp", army=True, fleet=False),
        Path(origin="mos", dest="sev", army=True, fleet=False),
        Path(origin="mos", dest="war", army=True, fleet=False),
        Path(origin="mun", dest="sil", army=True, fleet=False),
        Path(origin="mun", dest="boh", army=True, fleet=False),
        Path(origin="mun", dest="kie", army=True, fleet=False),
        Path(origin="mun", dest="ber", army=True, fleet=False),
        Path(origin="mun", dest="tyr", army=True, fleet=False),
        Path(origin="mun", dest="ruh", army=True, fleet=False),
        Path(origin="mun", dest="bur", army=True, fleet=False),
        Path(origin="naf", dest="tun", army=True, fleet=True),
        Path(origin="naf", dest="mao", army=False, fleet=True),
        Path(origin="naf", dest="wes", army=False, fleet=True),
        Path(origin="nao", dest="lvp", army=False, fleet=True),
        Path(origin="nao", dest="mao", army=False, fleet=True),
        Path(origin="nao", dest="cly", army=False, fleet=True),
        Path(origin="nao", dest="iri", army=False, fleet=True),
        Path(origin="nao", dest="nwg", army=False, fleet=True),
        Path(origin="nap", dest="ion", army=False, fleet=True),
        Path(origin="nap", dest="rom", army=True, fleet=True),
        Path(origin="nap", dest="tys", army=False, fleet=True),
        Path(origin="nap", dest="apu", army=True, fleet=True),
        Path(origin="nth", dest="yor", army=False, fleet=True),
        Path(origin="nth", dest="nwy", army=False, fleet=True),
        Path(origin="nth", dest="nwg", army=False, fleet=True),
        Path(origin="nth", dest="ska", army=False, fleet=True),
        Path(origin="nth", dest="lon", army=False, fleet=True),
        Path(origin="nth", dest="bel", army=False, fleet=True),
        Path(origin="nth", dest="den", army=False, fleet=True),
        Path(origin="nth", dest="edi", army=False, fleet=True),
        Path(origin="nth", dest="eng", army=False, fleet=True),
        Path(origin="nth", dest="hel", army=False, fleet=True),
        Path(origin="nth", dest="hol", army=False, fleet=True),
        Path(origin="nwg", dest="edi", army=False, fleet=True),
        Path(origin="nwg", dest="cly", army=False, fleet=True),
        Path(origin="nwg", dest="nth", army=False, fleet=True),
        Path(origin="nwg", dest="bar", army=False, fleet=True),
        Path(origin="nwg", dest="nao", army=False, fleet=True),
        Path(origin="nwg", dest="nwy", army=False, fleet=True),
        Path(origin="nwy", dest="nth", army=False, fleet=True),
        Path(origin="nwy", dest="nwg", army=False, fleet=True),
        Path(origin="nwy", dest="bar", army=False, fleet=True),
        Path(origin="nwy", dest="stp", army=True, fleet=False),
        Path(origin="nwy", dest="stp_nc", army=False, fleet=True),
        Path(origin="nwy", dest="ska", army=False, fleet=True),
        Path(origin="nwy", dest="fin", army=True, fleet=False),
        Path(origin="nwy", dest="swe", army=True, fleet=True),
        Path(origin="par", dest="bur", army=True, fleet=False),
        Path(origin="par", dest="pic", army=True, fleet=False),
        Path(origin="par", dest="gas", army=True, fleet=False),
        Path(origin="par", dest="bre", army=True, fleet=False),
        Path(origin="pic", dest="eng", army=False, fleet=True),
        Path(origin="pic", dest="bel", army=True, fleet=True),
        Path(origin="pic", dest="bur", army=True, fleet=False),
        Path(origin="pic", dest="bre", army=True, fleet=True),
        Path(origin="pic", dest="par", army=True, fleet=False),
        Path(origin="pie", dest="lyo", army=False, fleet=True),
        Path(origin="pie", dest="ven", army=True, fleet=False),
        Path(origin="pie", dest="mar", army=True, fleet=True),
        Path(origin="pie", dest="tyr", army=True, fleet=False),
        Path(origin="pie", dest="tus", army=True, fleet=True),
        Path(origin="por", dest="spa_nc", army=False, fleet=True),
        Path(origin="por", dest="mao", army=False, fleet=True),
        Path(origin="por", dest="spa", army=True, fleet=False),
        Path(origin="por", dest="spa_sc", army=False, fleet=True),
        Path(origin="pru", dest="lvn", army=True, fleet=True),
        Path(origin="pru", dest="war", army=True, fleet=False),
        Path(origin="pru", dest="ber", army=True, fleet=True),
        Path(origin="pru", dest="bal", army=False, fleet=True),
        Path(origin="pru", dest="sil", army=True, fleet=False),
        Path(origin="rom", dest="ven", army=True, fleet=False),
        Path(origin="rom", dest="tus", army=True, fleet=True),
        Path(origin="rom", dest="tys", army=False, fleet=True),
        Path(origin="rom", dest="apu", army=True, fleet=False),
        Path(origin="rom", dest="nap", army=True, fleet=True),
        Path(origin="ruh", dest="hol", army=True, fleet=False),
        Path(origin="ruh", dest="mun", army=True, fleet=False),
        Path(origin="ruh", dest="kie", army=True, fleet=False),
        Path(origin="ruh", dest="bur", army=True, fleet=False),
        Path(origin="ruh", dest="bel", army=True, fleet=False),
        Path(origin="rum", dest="bud", army=True, fleet=False),
        Path(origin="rum", dest="ukr", army=True, fleet=False),
        Path(origin="rum", dest="bla", army=False, fleet=True),
        Path(origin="rum", dest="gal", army=True, fleet=False),
        Path(origin="rum", dest="bul", army=True, fleet=False),
        Path(origin="rum", dest="ser", army=True, fleet=False),
        Path(origin="rum", dest="bul", army=True, fleet=False),
        Path(origin="rum", dest="bul_ec", army=False, fleet=True),
        Path(origin="rum", dest="sev", army=True, fleet=True),
        Path(origin="ser", dest="bul", army=True, fleet=False),
        Path(origin="ser", dest="gre", army=True, fleet=False),
        Path(origin="ser", dest="tri", army=True, fleet=False),
        Path(origin="ser", dest="bud", army=True, fleet=False),
        Path(origin="ser", dest="alb", army=True, fleet=False),
        Path(origin="ser", dest="rum", army=True, fleet=False),
        Path(origin="sev", dest="mos", army=True, fleet=False),
        Path(origin="sev", dest="rum", army=True, fleet=True),
        Path(origin="sev", dest="bla", army=False, fleet=True),
        Path(origin="sev", dest="arm", army=True, fleet=True),
        Path(origin="sev", dest="ukr", army=True, fleet=False),
        Path(origin="sil", dest="war", army=True, fleet=False),
        Path(origin="sil", dest="gal", army=True, fleet=False),
        Path(origin="sil", dest="pru", army=True, fleet=False),
        Path(origin="sil", dest="mun", army=True, fleet=False),
        Path(origin="sil", dest="ber", army=True, fleet=False),
        Path(origin="sil", dest="boh", army=True, fleet=False),
        Path(origin="ska", dest="nth", army=False, fleet=True),
        Path(origin="ska", dest="nwy", army=False, fleet=True),
        Path(origin="ska", dest="swe", army=False, fleet=True),
        Path(origin="ska", dest="den", army=False, fleet=True),
        Path(origin="smy", dest="con", army=True, fleet=True),
        Path(origin="smy", dest="ank", army=True, fleet=False),
        Path(origin="smy", dest="arm", army=True, fleet=False),
        Path(origin="smy", dest="syr", army=True, fleet=True),
        Path(origin="smy", dest="aeg", army=False, fleet=True),
        Path(origin="smy", dest="eas", army=False, fleet=True),
        Path(origin="spa", dest="gas", army=True, fleet=False),
        Path(origin="spa", dest="mar", army=True, fleet=False),
        Path(origin="spa", dest="por", army=True, fleet=False),
        Path(origin="spa", dest="mao", army=False, fleet=True),
        Path(origin="spa", dest="lyo", army=False, fleet=True),
        Path(origin="spa", dest="wes", army=False, fleet=True),
        Path(origin="spa_nc", dest="gas", army=False, fleet=True),
        Path(origin="spa_nc", dest="por", army=False, fleet=True),
        Path(origin="spa_nc", dest="mao", army=False, fleet=True),
        Path(origin="spa_sc", dest="mar", army=False, fleet=True),
        Path(origin="spa_sc", dest="mao", army=False, fleet=True),
        Path(origin="spa_sc", dest="lyo", army=False, fleet=True),
        Path(origin="spa_sc", dest="wes", army=False, fleet=True),
        Path(origin="spa_sc", dest="por", army=False, fleet=True),
        Path(origin="stp", dest="nwy", army=True, fleet=False),
        Path(origin="stp", dest="fin", army=True, fleet=False),
        Path(origin="stp", dest="lvn", army=True, fleet=False),
        Path(origin="stp", dest="mos", army=True, fleet=False),
        Path(origin="stp", dest="bar", army=False, fleet=True),
        Path(origin="stp", dest="bot", army=False, fleet=True),
        Path(origin="stp_nc", dest="bar", army=False, fleet=True),
        Path(origin="stp_nc", dest="nwy", army=False, fleet=True),
        Path(origin="stp_sc", dest="fin", army=False, fleet=True),
        Path(origin="stp_sc", dest="lvn", army=False, fleet=True),
        Path(origin="stp_sc", dest="bot", army=False, fleet=True),
        Path(origin="swe", dest="ska", army=False, fleet=True),
        Path(origin="swe", dest="den", army=True, fleet=True),
        Path(origin="swe", dest="nwy", army=True, fleet=True),
        Path(origin="swe", dest="fin", army=True, fleet=True),
        Path(origin="swe", dest="bot", army=False, fleet=True),
        Path(origin="swe", dest="bal", army=False, fleet=True),
        Path(origin="syr", dest="arm", army=True, fleet=False),
        Path(origin="syr", dest="eas", army=False, fleet=True),
        Path(origin="syr", dest="smy", army=True, fleet=True),
        Path(origin="tri", dest="vie", army=True, fleet=False),
        Path(origin="tri", dest="alb", army=True, fleet=True),
        Path(origin="tri", dest="adr", army=False, fleet=True),
        Path(origin="tri", dest="ven", army=True, fleet=True),
        Path(origin="tri", dest="ser", army=True, fleet=False),
        Path(origin="tri", dest="tyr", army=True, fleet=False),
        Path(origin="tri", dest="bud", army=True, fleet=False),
        Path(origin="tun", dest="wes", army=False, fleet=True),
        Path(origin="tun", dest="tys", army=False, fleet=True),
        Path(origin="tun", dest="ion", army=False, fleet=True),
        Path(origin="tun", dest="naf", army=True, fleet=True),
        Path(origin="tus", dest="lyo", army=False, fleet=True),
        Path(origin="tus", dest="ven", army=True, fleet=False),
        Path(origin="tus", dest="tys", army=False, fleet=True),
        Path(origin="tus", dest="pie", army=True, fleet=True),
        Path(origin="tus", dest="rom", army=True, fleet=True),
        Path(origin="tyr", dest="vie", army=True, fleet=False),
        Path(origin="tyr", dest="tri", army=True, fleet=False),
        Path(origin="tyr", dest="mun", army=True, fleet=False),
        Path(origin="tyr", dest="boh", army=True, fleet=False),
        Path(origin="tyr", dest="ven", army=True, fleet=False),
        Path(origin="tyr", dest="pie", army=True, fleet=False),
        Path(origin="tys", dest="tus", army=False, fleet=True),
        Path(origin="tys", dest="ion", army=False, fleet=True),
        Path(origin="tys", dest="rom", army=False, fleet=True),
        Path(origin="tys", dest="tun", army=False, fleet=True),
        Path(origin="tys", dest="wes", army=False, fleet=True),
        Path(origin="tys", dest="lyo", army=False, fleet=True),
        Path(origin="tys", dest="nap", army=False, fleet=True),
        Path(origin="ukr", dest="sev", army=True, fleet=False),
        Path(origin="ukr", dest="mos", army=True, fleet=False),
        Path(origin="ukr", dest="rum", army=True, fleet=False),
        Path(origin="ukr", dest="gal", army=True, fleet=False),
        Path(origin="ukr", dest="war", army=True, fleet=False),
        Path(origin="ven", dest="tri", army=True, fleet=True),
        Path(origin="ven", dest="adr", army=False, fleet=True),
        Path(origin="ven", dest="apu", army=True, fleet=True),
        Path(origin="ven", dest="tyr", army=True, fleet=False),
        Path(origin="ven", dest="pie", army=True, fleet=False),
        Path(origin="ven", dest="rom", army=True, fleet=False),
        Path(origin="ven", dest="tus", army=True, fleet=False),
        Path(origin="vie", dest="gal", army=True, fleet=False),
        Path(origin="vie", dest="tyr", army=True, fleet=False),
        Path(origin="vie", dest="tri", army=True, fleet=False),
        Path(origin="vie", dest="boh", army=True, fleet=False),
        Path(origin="vie", dest="bud", army=True, fleet=False),
        Path(origin="wal", dest="eng", army=False, fleet=True),
        Path(origin="wal", dest="lvp", army=True, fleet=True),
        Path(origin="wal", dest="iri", army=False, fleet=True),
        Path(origin="wal", dest="lon", army=True, fleet=True),
        Path(origin="wal", dest="yor", army=True, fleet=False),
        Path(origin="war", dest="ukr", army=True, fleet=False),
        Path(origin="war", dest="pru", army=True, fleet=False),
        Path(origin="war", dest="gal", army=True, fleet=False),
        Path(origin="war", dest="mos", army=True, fleet=False),
        Path(origin="war", dest="sil", army=True, fleet=False),
        Path(origin="war", dest="lvn", army=True, fleet=False),
        Path(origin="wes", dest="tys", army=False, fleet=True),
        Path(origin="wes", dest="mao", army=False, fleet=True),
        Path(origin="wes", dest="tun", army=False, fleet=True),
        Path(origin="wes", dest="spa", army=True, fleet=False),
        Path(origin="wes", dest="spa_sc", army=False, fleet=True),
        Path(origin="wes", dest="naf", army=False, fleet=True),
        Path(origin="wes", dest="lyo", army=False, fleet=True),
        Path(origin="yor", dest="edi", army=True, fleet=True),
        Path(origin="yor", dest="wal", army=True, fleet=False),
        Path(origin="yor", dest="lon", army=True, fleet=True),
        Path(origin="yor", dest="nth", army=False, fleet=True),
        Path(origin="yor", dest="lvp", army=True, fleet=False),
    ]
    session.add_all(paths)
    session.commit()
