from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.future import select

from models.path_model import Path
from models.power_model import Power
from models.province_model import Coast, Inland, Province, Water


async def generate_master_data(db: AsyncSession) -> None:
    list_of_power = [
        Power(symbol="a", name="Austria", adjective="Austrian"),
        Power(symbol="e", name="England", adjective="English"),
        Power(symbol="f", name="France", adjective="French"),
        Power(symbol="g", name="Germany", adjective="German"),
        Power(symbol="i", name="Italy", adjective="Italian"),
        Power(symbol="r", name="Russia", adjective="Russian"),
        Power(symbol="t", name="Turkey", adjective="Turkish"),
    ]
    db.add_all(list_of_power)
    await db.commit()

    power_result = await db.execute(select(Power))
    powers: dict[str, Power] = {power.symbol: power for power in power_result.scalars().all()}

    list_of_province = [
        Water(abbr="adr", name="Adriatic Water", jname="アドリア海"),
        Water(abbr="aeg", name="Aegean Water", jname="エーゲ海"),
        Coast(abbr="alb", name="Albania", jname="アルバニア"),
        Coast(abbr="ank", name="Ankara", jname="アンカラ", suppliable=True, region=powers["t"]),
        Coast(abbr="apu", name="Apulia", jname="アプリア", region=powers["i"]),
        Coast(abbr="arm", name="Armenia", jname="アルメニア", region=powers["t"]),
        Water(abbr="bal", name="Baltic Water", jname="バルト海"),
        Water(abbr="bar", name="Barents Water", jname="バレンツ海"),
        Coast(abbr="bel", name="Belgium", jname="ベルギー", suppliable=True),
        Coast(abbr="ber", name="Berlin", jname="ベルリン", suppliable=True, region=powers["g"]),
        Water(abbr="bla", name="Black Water", jname="黒海"),
        Inland(abbr="boh", name="Bohemia", jname="ボヘミア", region=powers["a"]),
        Water(abbr="bot", name="Gulf of Bothnia", jname="ボスニア湾"),
        Coast(abbr="bre", name="Brest", jname="ブレスト", suppliable=True, region=powers["f"]),
        Inland(abbr="bud", name="Budapest", jname="ブダペスト", suppliable=True, region=powers["a"]),
        Coast(abbr="bul", name="Bulgaria", jname="ブルガリア", suppliable=True),
        Coast(abbr="bul_ec", name="Bulgaria(EC)", jname="ブルガリア(EC)"),
        Coast(abbr="bul_sc", name="Bulgaria(SC)", jname="ブルガリア(SC)"),
        Inland(abbr="bur", name="Burgundy", jname="ブルゴーニュ", region=powers["f"]),
        Coast(abbr="cly", name="Clyde", jname="クライド", region=powers["e"]),
        Coast(abbr="con", name="Constantinople", jname="コンスタンティノープル", suppliable=True, region=powers["t"]),
        Coast(abbr="den", name="Denmark", jname="デンマーク", suppliable=True),
        Water(abbr="eas", name="Eastern Mediterranean", jname="東地中海"),
        Coast(abbr="edi", name="Edinburgh", jname="エディンバラ", suppliable=True, region=powers["e"]),
        Water(abbr="eng", name="English Channel", jname="イギリス海峡"),
        Coast(abbr="fin", name="Finland", jname="フィンランド", region=powers["r"]),
        Inland(abbr="gal", name="Galicia", jname="ガリツィア", region=powers["a"]),
        Coast(abbr="gas", name="Gascony", jname="ガスコーニュ", region=powers["f"]),
        Coast(abbr="gre", name="Greece", jname="ギリシア", suppliable=True),
        Water(abbr="hel", name="Helgoland Bight", jname="ヘルゴラント湾"),
        Coast(abbr="hol", name="Holland", jname="オランダ", suppliable=True),
        Water(abbr="ion", name="Ionian Water", jname="イオニア海"),
        Water(abbr="iri", name="Irish Water", jname="アイリッシュ海"),
        Coast(abbr="kie", name="Kiel", jname="キール", suppliable=True, region=powers["g"]),
        Coast(abbr="lon", name="London", jname="ロンドン", suppliable=True, region=powers["e"]),
        Coast(abbr="lvn", name="Livonia", jname="リヴォニア", region=powers["r"]),
        Coast(abbr="lvp", name="Liverpool", jname="リヴァプール", suppliable=True, region=powers["e"]),
        Water(abbr="lyo", name="Gulf of Lyon", jname="リオン湾"),
        Water(abbr="mao", name="Mid-Atlantic Ocean", jname="中大西洋"),
        Coast(abbr="mar", name="Marseilles", jname="マルセイユ", suppliable=True, region=powers["f"]),
        Inland(abbr="mos", name="Moscow", jname="モスクワ", suppliable=True, region=powers["r"]),
        Inland(abbr="mun", name="Munich", jname="ミュンヘン", suppliable=True, region=powers["g"]),
        Coast(abbr="naf", name="North Africa", jname="北アフリカ"),
        Water(abbr="nao", name="North Atlantic Ocean", jname="北大西洋"),
        Coast(abbr="nap", name="Naples", jname="ナポリ", suppliable=True, region=powers["i"]),
        Water(abbr="nth", name="North Water", jname="北海"),
        Water(abbr="nwg", name="Norwegian Water", jname="ノルウェー海"),
        Coast(abbr="nwy", name="Norway", jname="ノルウェー", suppliable=True),
        Inland(abbr="par", name="Paris", jname="パリ", suppliable=True, region=powers["f"]),
        Coast(abbr="pic", name="Picardy", jname="ピカルディ", region=powers["f"]),
        Coast(abbr="pie", name="Piedmont", jname="ピエモンテ", region=powers["i"]),
        Coast(abbr="por", name="Portugal", jname="ポルトガル", suppliable=True),
        Coast(abbr="pru", name="Prussia", jname="プロイセン", region=powers["g"]),
        Coast(abbr="rom", name="Rome", jname="ローマ", suppliable=True, region=powers["i"]),
        Inland(abbr="ruh", name="Ruhrl", jname="ルール", region=powers["g"]),
        Coast(abbr="rum", name="Rumania", jname="ルーマニア", suppliable=True),
        Inland(abbr="ser", name="Serbia", jname="セルビア", suppliable=True),
        Coast(abbr="sev", name="Sevastopol", jname="セヴァストポリ", suppliable=True, region=powers["r"]),
        Inland(abbr="sil", name="Silesia", jname="シレジア", region=powers["g"]),
        Water(abbr="ska", name="Skagerrak", jname="スカゲラク海峡"),
        Coast(abbr="smy", name="Smyrna", jname="スミルナ", suppliable=True, region=powers["t"]),
        Coast(abbr="spa", name="Spain", jname="スペイン", suppliable=True),
        Coast(abbr="spa_nc", name="Spain(NC)", jname="スペイン(NC)"),
        Coast(abbr="spa_sc", name="Spain(SC)", jname="スペイン(SC)"),
        Coast(abbr="stp", name="St. Petersburg", jname="サンクトペテルブルク", suppliable=True, region=powers["r"]),
        Coast(abbr="stp_nc", name="St. Petersburg(NC)", jname="サンクトペテルブルク(NC)"),
        Coast(abbr="stp_sc", name="St. Petersburg(SC)", jname="サンクトペテルブルク(SC)"),
        Coast(abbr="swe", name="Sweden", jname="スウェーデン", suppliable=True),
        Coast(abbr="syr", name="Syria", jname="シリア", region=powers["t"]),
        Coast(abbr="tri", name="Trieste", jname="トリエステ", suppliable=True, region=powers["a"]),
        Coast(abbr="tun", name="Tunis", jname="チュニス", suppliable=True),
        Coast(abbr="tus", name="Tuscany", jname="トスカーナ", region=powers["i"]),
        Inland(abbr="tyr", name="Tyrolia", jname="ティロル", region=powers["a"]),
        Water(abbr="tys", name="Tyrrhenian Water", jname="ティレニア海"),
        Inland(abbr="ukr", name="Ukraine", jname="ウクライナ", region=powers["r"]),
        Coast(abbr="ven", name="Venice", jname="ヴェネツィア", suppliable=True, region=powers["i"]),
        Inland(abbr="vie", name="Vienna", jname="ウィーン", suppliable=True, region=powers["a"]),
        Coast(abbr="wal", name="Wales", jname="ウェールズ", region=powers["e"]),
        Inland(abbr="war", name="Warsaw", jname="ワルシャワ", suppliable=True, region=powers["r"]),
        Water(abbr="wes", name="Western Mediterranean", jname="西地中海"),
        Coast(abbr="yor", name="Yorkshire", jname="ヨークシャー", region=powers["e"]),
    ]
    db.add_all(list_of_province)
    await db.commit()

    province_result = await db.execute(select(Province))
    provinces: dict[str, Province] = {province.abbr: province for province in province_result.scalars().all()}

    paths = [
        Path(origin=provinces["adr"], dest=provinces["apu"], army=False, fleet=True),
        Path(origin=provinces["adr"], dest=provinces["ion"], army=False, fleet=True),
        Path(origin=provinces["adr"], dest=provinces["alb"], army=False, fleet=True),
        Path(origin=provinces["adr"], dest=provinces["tri"], army=False, fleet=True),
        Path(origin=provinces["adr"], dest=provinces["ven"], army=False, fleet=True),
        Path(origin=provinces["aeg"], dest=provinces["gre"], army=False, fleet=True),
        Path(origin=provinces["aeg"], dest=provinces["smy"], army=False, fleet=True),
        Path(origin=provinces["aeg"], dest=provinces["bul_sc"], army=False, fleet=True),
        Path(origin=provinces["aeg"], dest=provinces["eas"], army=False, fleet=True),
        Path(origin=provinces["aeg"], dest=provinces["con"], army=False, fleet=True),
        Path(origin=provinces["aeg"], dest=provinces["ion"], army=False, fleet=True),
        Path(origin=provinces["alb"], dest=provinces["adr"], army=False, fleet=True),
        Path(origin=provinces["alb"], dest=provinces["gre"], army=True, fleet=True),
        Path(origin=provinces["alb"], dest=provinces["ser"], army=True, fleet=False),
        Path(origin=provinces["alb"], dest=provinces["ion"], army=False, fleet=True),
        Path(origin=provinces["alb"], dest=provinces["tri"], army=True, fleet=True),
        Path(origin=provinces["ank"], dest=provinces["smy"], army=True, fleet=False),
        Path(origin=provinces["ank"], dest=provinces["bla"], army=False, fleet=True),
        Path(origin=provinces["ank"], dest=provinces["arm"], army=True, fleet=True),
        Path(origin=provinces["ank"], dest=provinces["con"], army=True, fleet=True),
        Path(origin=provinces["apu"], dest=provinces["rom"], army=True, fleet=False),
        Path(origin=provinces["apu"], dest=provinces["ion"], army=False, fleet=True),
        Path(origin=provinces["apu"], dest=provinces["ven"], army=True, fleet=True),
        Path(origin=provinces["apu"], dest=provinces["adr"], army=False, fleet=True),
        Path(origin=provinces["apu"], dest=provinces["nap"], army=True, fleet=True),
        Path(origin=provinces["arm"], dest=provinces["bla"], army=False, fleet=True),
        Path(origin=provinces["arm"], dest=provinces["syr"], army=True, fleet=False),
        Path(origin=provinces["arm"], dest=provinces["ank"], army=True, fleet=True),
        Path(origin=provinces["arm"], dest=provinces["sev"], army=True, fleet=True),
        Path(origin=provinces["arm"], dest=provinces["smy"], army=True, fleet=False),
        Path(origin=provinces["bal"], dest=provinces["den"], army=False, fleet=True),
        Path(origin=provinces["bal"], dest=provinces["ber"], army=False, fleet=True),
        Path(origin=provinces["bal"], dest=provinces["kie"], army=False, fleet=True),
        Path(origin=provinces["bal"], dest=provinces["swe"], army=False, fleet=True),
        Path(origin=provinces["bal"], dest=provinces["lvn"], army=False, fleet=True),
        Path(origin=provinces["bal"], dest=provinces["bot"], army=False, fleet=True),
        Path(origin=provinces["bal"], dest=provinces["pru"], army=False, fleet=True),
        Path(origin=provinces["bar"], dest=provinces["nwy"], army=False, fleet=True),
        Path(origin=provinces["bar"], dest=provinces["nwg"], army=False, fleet=True),
        Path(origin=provinces["bar"], dest=provinces["stp_nc"], army=False, fleet=True),
        Path(origin=provinces["bel"], dest=provinces["eng"], army=False, fleet=True),
        Path(origin=provinces["bel"], dest=provinces["pic"], army=True, fleet=True),
        Path(origin=provinces["bel"], dest=provinces["hol"], army=True, fleet=True),
        Path(origin=provinces["bel"], dest=provinces["ruh"], army=True, fleet=False),
        Path(origin=provinces["bel"], dest=provinces["nth"], army=False, fleet=True),
        Path(origin=provinces["bel"], dest=provinces["bur"], army=True, fleet=False),
        Path(origin=provinces["ber"], dest=provinces["bal"], army=False, fleet=True),
        Path(origin=provinces["ber"], dest=provinces["kie"], army=True, fleet=True),
        Path(origin=provinces["ber"], dest=provinces["mun"], army=True, fleet=False),
        Path(origin=provinces["ber"], dest=provinces["sil"], army=True, fleet=False),
        Path(origin=provinces["ber"], dest=provinces["pru"], army=True, fleet=True),
        Path(origin=provinces["bla"], dest=provinces["arm"], army=False, fleet=True),
        Path(origin=provinces["bla"], dest=provinces["con"], army=False, fleet=True),
        Path(origin=provinces["bla"], dest=provinces["ank"], army=False, fleet=True),
        Path(origin=provinces["bla"], dest=provinces["sev"], army=False, fleet=True),
        Path(origin=provinces["bla"], dest=provinces["rum"], army=False, fleet=True),
        Path(origin=provinces["bla"], dest=provinces["bul_ec"], army=False, fleet=True),
        Path(origin=provinces["boh"], dest=provinces["mun"], army=True, fleet=False),
        Path(origin=provinces["boh"], dest=provinces["sil"], army=True, fleet=False),
        Path(origin=provinces["boh"], dest=provinces["gal"], army=True, fleet=False),
        Path(origin=provinces["boh"], dest=provinces["vie"], army=True, fleet=False),
        Path(origin=provinces["boh"], dest=provinces["tyr"], army=True, fleet=False),
        Path(origin=provinces["bot"], dest=provinces["swe"], army=False, fleet=True),
        Path(origin=provinces["bot"], dest=provinces["fin"], army=False, fleet=True),
        Path(origin=provinces["bot"], dest=provinces["lvn"], army=False, fleet=True),
        Path(origin=provinces["bot"], dest=provinces["stp_sc"], army=False, fleet=True),
        Path(origin=provinces["bot"], dest=provinces["bal"], army=False, fleet=True),
        Path(origin=provinces["bre"], dest=provinces["mao"], army=False, fleet=True),
        Path(origin=provinces["bre"], dest=provinces["eng"], army=False, fleet=True),
        Path(origin=provinces["bre"], dest=provinces["par"], army=True, fleet=False),
        Path(origin=provinces["bre"], dest=provinces["pic"], army=True, fleet=True),
        Path(origin=provinces["bre"], dest=provinces["gas"], army=True, fleet=True),
        Path(origin=provinces["bud"], dest=provinces["tri"], army=True, fleet=False),
        Path(origin=provinces["bud"], dest=provinces["ser"], army=True, fleet=False),
        Path(origin=provinces["bud"], dest=provinces["gal"], army=True, fleet=False),
        Path(origin=provinces["bud"], dest=provinces["vie"], army=True, fleet=False),
        Path(origin=provinces["bud"], dest=provinces["rum"], army=True, fleet=False),
        Path(origin=provinces["bul"], dest=provinces["con"], army=True, fleet=False),
        Path(origin=provinces["bul"], dest=provinces["ser"], army=True, fleet=False),
        Path(origin=provinces["bul"], dest=provinces["gre"], army=True, fleet=False),
        Path(origin=provinces["bul"], dest=provinces["rum"], army=True, fleet=False),
        Path(origin=provinces["bul_ec"], dest=provinces["con"], army=False, fleet=True),
        Path(origin=provinces["bul_ec"], dest=provinces["bla"], army=False, fleet=True),
        Path(origin=provinces["bul_ec"], dest=provinces["rum"], army=False, fleet=True),
        Path(origin=provinces["bul_sc"], dest=provinces["con"], army=False, fleet=True),
        Path(origin=provinces["bul_sc"], dest=provinces["aeg"], army=False, fleet=True),
        Path(origin=provinces["bul_sc"], dest=provinces["gre"], army=False, fleet=True),
        Path(origin=provinces["bur"], dest=provinces["par"], army=True, fleet=False),
        Path(origin=provinces["bur"], dest=provinces["pic"], army=True, fleet=False),
        Path(origin=provinces["bur"], dest=provinces["gas"], army=True, fleet=False),
        Path(origin=provinces["bur"], dest=provinces["ruh"], army=True, fleet=False),
        Path(origin=provinces["bur"], dest=provinces["bel"], army=True, fleet=False),
        Path(origin=provinces["bur"], dest=provinces["mar"], army=True, fleet=False),
        Path(origin=provinces["bur"], dest=provinces["mun"], army=True, fleet=False),
        Path(origin=provinces["cly"], dest=provinces["edi"], army=True, fleet=True),
        Path(origin=provinces["cly"], dest=provinces["nao"], army=False, fleet=True),
        Path(origin=provinces["cly"], dest=provinces["lvp"], army=True, fleet=True),
        Path(origin=provinces["cly"], dest=provinces["nwg"], army=False, fleet=True),
        Path(origin=provinces["con"], dest=provinces["aeg"], army=False, fleet=True),
        Path(origin=provinces["con"], dest=provinces["ank"], army=True, fleet=True),
        Path(origin=provinces["con"], dest=provinces["bla"], army=False, fleet=True),
        Path(origin=provinces["con"], dest=provinces["bul"], army=True, fleet=False),
        Path(origin=provinces["con"], dest=provinces["bul_sc"], army=False, fleet=True),
        Path(origin=provinces["con"], dest=provinces["bul_ec"], army=False, fleet=True),
        Path(origin=provinces["con"], dest=provinces["smy"], army=True, fleet=True),
        Path(origin=provinces["den"], dest=provinces["swe"], army=True, fleet=True),
        Path(origin=provinces["den"], dest=provinces["hel"], army=False, fleet=True),
        Path(origin=provinces["den"], dest=provinces["bal"], army=False, fleet=True),
        Path(origin=provinces["den"], dest=provinces["nth"], army=False, fleet=True),
        Path(origin=provinces["den"], dest=provinces["ska"], army=False, fleet=True),
        Path(origin=provinces["den"], dest=provinces["kie"], army=True, fleet=True),
        Path(origin=provinces["eas"], dest=provinces["syr"], army=False, fleet=True),
        Path(origin=provinces["eas"], dest=provinces["aeg"], army=False, fleet=True),
        Path(origin=provinces["eas"], dest=provinces["ion"], army=False, fleet=True),
        Path(origin=provinces["eas"], dest=provinces["smy"], army=False, fleet=True),
        Path(origin=provinces["edi"], dest=provinces["yor"], army=True, fleet=True),
        Path(origin=provinces["edi"], dest=provinces["nth"], army=False, fleet=True),
        Path(origin=provinces["edi"], dest=provinces["nwg"], army=False, fleet=True),
        Path(origin=provinces["edi"], dest=provinces["cly"], army=True, fleet=True),
        Path(origin=provinces["edi"], dest=provinces["lvp"], army=True, fleet=False),
        Path(origin=provinces["eng"], dest=provinces["mao"], army=False, fleet=True),
        Path(origin=provinces["eng"], dest=provinces["lon"], army=False, fleet=True),
        Path(origin=provinces["eng"], dest=provinces["nth"], army=False, fleet=True),
        Path(origin=provinces["eng"], dest=provinces["bel"], army=False, fleet=True),
        Path(origin=provinces["eng"], dest=provinces["pic"], army=False, fleet=True),
        Path(origin=provinces["eng"], dest=provinces["bre"], army=False, fleet=True),
        Path(origin=provinces["eng"], dest=provinces["iri"], army=False, fleet=True),
        Path(origin=provinces["eng"], dest=provinces["wal"], army=False, fleet=True),
        Path(origin=provinces["fin"], dest=provinces["bot"], army=False, fleet=True),
        Path(origin=provinces["fin"], dest=provinces["swe"], army=True, fleet=True),
        Path(origin=provinces["fin"], dest=provinces["nwy"], army=True, fleet=False),
        Path(origin=provinces["fin"], dest=provinces["stp_sc"], army=False, fleet=True),
        Path(origin=provinces["fin"], dest=provinces["stp"], army=True, fleet=False),
        Path(origin=provinces["gal"], dest=provinces["boh"], army=True, fleet=False),
        Path(origin=provinces["gal"], dest=provinces["sil"], army=True, fleet=False),
        Path(origin=provinces["gal"], dest=provinces["rum"], army=True, fleet=False),
        Path(origin=provinces["gal"], dest=provinces["ukr"], army=True, fleet=False),
        Path(origin=provinces["gal"], dest=provinces["war"], army=True, fleet=False),
        Path(origin=provinces["gal"], dest=provinces["vie"], army=True, fleet=False),
        Path(origin=provinces["gal"], dest=provinces["bud"], army=True, fleet=False),
        Path(origin=provinces["gas"], dest=provinces["mao"], army=False, fleet=True),
        Path(origin=provinces["gas"], dest=provinces["spa"], army=True, fleet=False),
        Path(origin=provinces["gas"], dest=provinces["spa_nc"], army=False, fleet=True),
        Path(origin=provinces["gas"], dest=provinces["bre"], army=True, fleet=True),
        Path(origin=provinces["gas"], dest=provinces["bur"], army=True, fleet=False),
        Path(origin=provinces["gas"], dest=provinces["mar"], army=True, fleet=False),
        Path(origin=provinces["gas"], dest=provinces["par"], army=True, fleet=False),
        Path(origin=provinces["gre"], dest=provinces["alb"], army=True, fleet=True),
        Path(origin=provinces["gre"], dest=provinces["ion"], army=False, fleet=True),
        Path(origin=provinces["gre"], dest=provinces["ser"], army=True, fleet=False),
        Path(origin=provinces["gre"], dest=provinces["aeg"], army=False, fleet=True),
        Path(origin=provinces["gre"], dest=provinces["bul"], army=True, fleet=False),
        Path(origin=provinces["gre"], dest=provinces["bul_sc"], army=False, fleet=True),
        Path(origin=provinces["hel"], dest=provinces["den"], army=False, fleet=True),
        Path(origin=provinces["hel"], dest=provinces["kie"], army=False, fleet=True),
        Path(origin=provinces["hel"], dest=provinces["nth"], army=False, fleet=True),
        Path(origin=provinces["hel"], dest=provinces["hol"], army=False, fleet=True),
        Path(origin=provinces["hol"], dest=provinces["hel"], army=False, fleet=True),
        Path(origin=provinces["hol"], dest=provinces["bel"], army=True, fleet=True),
        Path(origin=provinces["hol"], dest=provinces["nth"], army=False, fleet=True),
        Path(origin=provinces["hol"], dest=provinces["ruh"], army=True, fleet=False),
        Path(origin=provinces["hol"], dest=provinces["kie"], army=True, fleet=True),
        Path(origin=provinces["ion"], dest=provinces["nap"], army=False, fleet=True),
        Path(origin=provinces["ion"], dest=provinces["eas"], army=False, fleet=True),
        Path(origin=provinces["ion"], dest=provinces["gre"], army=False, fleet=True),
        Path(origin=provinces["ion"], dest=provinces["apu"], army=False, fleet=True),
        Path(origin=provinces["ion"], dest=provinces["alb"], army=False, fleet=True),
        Path(origin=provinces["ion"], dest=provinces["aeg"], army=False, fleet=True),
        Path(origin=provinces["ion"], dest=provinces["adr"], army=False, fleet=True),
        Path(origin=provinces["ion"], dest=provinces["tun"], army=False, fleet=True),
        Path(origin=provinces["ion"], dest=provinces["tys"], army=False, fleet=True),
        Path(origin=provinces["iri"], dest=provinces["mao"], army=False, fleet=True),
        Path(origin=provinces["iri"], dest=provinces["nao"], army=False, fleet=True),
        Path(origin=provinces["iri"], dest=provinces["lvp"], army=False, fleet=True),
        Path(origin=provinces["iri"], dest=provinces["eng"], army=False, fleet=True),
        Path(origin=provinces["iri"], dest=provinces["wal"], army=False, fleet=True),
        Path(origin=provinces["kie"], dest=provinces["ruh"], army=True, fleet=False),
        Path(origin=provinces["kie"], dest=provinces["hol"], army=True, fleet=True),
        Path(origin=provinces["kie"], dest=provinces["mun"], army=True, fleet=False),
        Path(origin=provinces["kie"], dest=provinces["hel"], army=False, fleet=True),
        Path(origin=provinces["kie"], dest=provinces["den"], army=True, fleet=True),
        Path(origin=provinces["kie"], dest=provinces["ber"], army=True, fleet=True),
        Path(origin=provinces["kie"], dest=provinces["bal"], army=False, fleet=True),
        Path(origin=provinces["lon"], dest=provinces["nth"], army=False, fleet=True),
        Path(origin=provinces["lon"], dest=provinces["eng"], army=False, fleet=True),
        Path(origin=provinces["lon"], dest=provinces["wal"], army=True, fleet=True),
        Path(origin=provinces["lon"], dest=provinces["yor"], army=True, fleet=True),
        Path(origin=provinces["lvn"], dest=provinces["bal"], army=False, fleet=True),
        Path(origin=provinces["lvn"], dest=provinces["stp"], army=True, fleet=False),
        Path(origin=provinces["lvn"], dest=provinces["stp_sc"], army=False, fleet=True),
        Path(origin=provinces["lvn"], dest=provinces["mos"], army=True, fleet=False),
        Path(origin=provinces["lvn"], dest=provinces["bot"], army=False, fleet=True),
        Path(origin=provinces["lvn"], dest=provinces["pru"], army=True, fleet=True),
        Path(origin=provinces["lvn"], dest=provinces["war"], army=True, fleet=False),
        Path(origin=provinces["lvp"], dest=provinces["yor"], army=True, fleet=False),
        Path(origin=provinces["lvp"], dest=provinces["cly"], army=True, fleet=True),
        Path(origin=provinces["lvp"], dest=provinces["wal"], army=True, fleet=True),
        Path(origin=provinces["lvp"], dest=provinces["nao"], army=False, fleet=True),
        Path(origin=provinces["lvp"], dest=provinces["iri"], army=False, fleet=True),
        Path(origin=provinces["lvp"], dest=provinces["edi"], army=True, fleet=False),
        Path(origin=provinces["lyo"], dest=provinces["mar"], army=False, fleet=True),
        Path(origin=provinces["lyo"], dest=provinces["spa_sc"], army=False, fleet=True),
        Path(origin=provinces["lyo"], dest=provinces["pie"], army=False, fleet=True),
        Path(origin=provinces["lyo"], dest=provinces["wes"], army=False, fleet=True),
        Path(origin=provinces["lyo"], dest=provinces["tys"], army=False, fleet=True),
        Path(origin=provinces["lyo"], dest=provinces["tus"], army=False, fleet=True),
        Path(origin=provinces["mao"], dest=provinces["spa_nc"], army=False, fleet=True),
        Path(origin=provinces["mao"], dest=provinces["bre"], army=False, fleet=True),
        Path(origin=provinces["mao"], dest=provinces["por"], army=False, fleet=True),
        Path(origin=provinces["mao"], dest=provinces["gas"], army=False, fleet=True),
        Path(origin=provinces["mao"], dest=provinces["nao"], army=False, fleet=True),
        Path(origin=provinces["mao"], dest=provinces["naf"], army=False, fleet=True),
        Path(origin=provinces["mao"], dest=provinces["wes"], army=False, fleet=True),
        Path(origin=provinces["mao"], dest=provinces["eng"], army=False, fleet=True),
        Path(origin=provinces["mao"], dest=provinces["iri"], army=False, fleet=True),
        Path(origin=provinces["mao"], dest=provinces["spa_sc"], army=False, fleet=True),
        Path(origin=provinces["mar"], dest=provinces["spa"], army=True, fleet=False),
        Path(origin=provinces["mar"], dest=provinces["pie"], army=True, fleet=True),
        Path(origin=provinces["mar"], dest=provinces["gas"], army=True, fleet=False),
        Path(origin=provinces["mar"], dest=provinces["spa_sc"], army=False, fleet=True),
        Path(origin=provinces["mar"], dest=provinces["bur"], army=True, fleet=False),
        Path(origin=provinces["mar"], dest=provinces["lyo"], army=False, fleet=True),
        Path(origin=provinces["mos"], dest=provinces["lvn"], army=True, fleet=False),
        Path(origin=provinces["mos"], dest=provinces["ukr"], army=True, fleet=False),
        Path(origin=provinces["mos"], dest=provinces["stp"], army=True, fleet=False),
        Path(origin=provinces["mos"], dest=provinces["sev"], army=True, fleet=False),
        Path(origin=provinces["mos"], dest=provinces["war"], army=True, fleet=False),
        Path(origin=provinces["mun"], dest=provinces["sil"], army=True, fleet=False),
        Path(origin=provinces["mun"], dest=provinces["boh"], army=True, fleet=False),
        Path(origin=provinces["mun"], dest=provinces["kie"], army=True, fleet=False),
        Path(origin=provinces["mun"], dest=provinces["ber"], army=True, fleet=False),
        Path(origin=provinces["mun"], dest=provinces["tyr"], army=True, fleet=False),
        Path(origin=provinces["mun"], dest=provinces["ruh"], army=True, fleet=False),
        Path(origin=provinces["mun"], dest=provinces["bur"], army=True, fleet=False),
        Path(origin=provinces["naf"], dest=provinces["tun"], army=True, fleet=True),
        Path(origin=provinces["naf"], dest=provinces["mao"], army=False, fleet=True),
        Path(origin=provinces["naf"], dest=provinces["wes"], army=False, fleet=True),
        Path(origin=provinces["nao"], dest=provinces["lvp"], army=False, fleet=True),
        Path(origin=provinces["nao"], dest=provinces["mao"], army=False, fleet=True),
        Path(origin=provinces["nao"], dest=provinces["cly"], army=False, fleet=True),
        Path(origin=provinces["nao"], dest=provinces["iri"], army=False, fleet=True),
        Path(origin=provinces["nao"], dest=provinces["nwg"], army=False, fleet=True),
        Path(origin=provinces["nap"], dest=provinces["ion"], army=False, fleet=True),
        Path(origin=provinces["nap"], dest=provinces["rom"], army=True, fleet=True),
        Path(origin=provinces["nap"], dest=provinces["tys"], army=False, fleet=True),
        Path(origin=provinces["nap"], dest=provinces["apu"], army=True, fleet=True),
        Path(origin=provinces["nth"], dest=provinces["yor"], army=False, fleet=True),
        Path(origin=provinces["nth"], dest=provinces["nwy"], army=False, fleet=True),
        Path(origin=provinces["nth"], dest=provinces["nwg"], army=False, fleet=True),
        Path(origin=provinces["nth"], dest=provinces["ska"], army=False, fleet=True),
        Path(origin=provinces["nth"], dest=provinces["lon"], army=False, fleet=True),
        Path(origin=provinces["nth"], dest=provinces["bel"], army=False, fleet=True),
        Path(origin=provinces["nth"], dest=provinces["den"], army=False, fleet=True),
        Path(origin=provinces["nth"], dest=provinces["edi"], army=False, fleet=True),
        Path(origin=provinces["nth"], dest=provinces["eng"], army=False, fleet=True),
        Path(origin=provinces["nth"], dest=provinces["hel"], army=False, fleet=True),
        Path(origin=provinces["nth"], dest=provinces["hol"], army=False, fleet=True),
        Path(origin=provinces["nwg"], dest=provinces["edi"], army=False, fleet=True),
        Path(origin=provinces["nwg"], dest=provinces["cly"], army=False, fleet=True),
        Path(origin=provinces["nwg"], dest=provinces["nth"], army=False, fleet=True),
        Path(origin=provinces["nwg"], dest=provinces["bar"], army=False, fleet=True),
        Path(origin=provinces["nwg"], dest=provinces["nao"], army=False, fleet=True),
        Path(origin=provinces["nwg"], dest=provinces["nwy"], army=False, fleet=True),
        Path(origin=provinces["nwy"], dest=provinces["nth"], army=False, fleet=True),
        Path(origin=provinces["nwy"], dest=provinces["nwg"], army=False, fleet=True),
        Path(origin=provinces["nwy"], dest=provinces["bar"], army=False, fleet=True),
        Path(origin=provinces["nwy"], dest=provinces["stp"], army=True, fleet=False),
        Path(origin=provinces["nwy"], dest=provinces["stp_nc"], army=False, fleet=True),
        Path(origin=provinces["nwy"], dest=provinces["ska"], army=False, fleet=True),
        Path(origin=provinces["nwy"], dest=provinces["fin"], army=True, fleet=False),
        Path(origin=provinces["nwy"], dest=provinces["swe"], army=True, fleet=True),
        Path(origin=provinces["par"], dest=provinces["bur"], army=True, fleet=False),
        Path(origin=provinces["par"], dest=provinces["pic"], army=True, fleet=False),
        Path(origin=provinces["par"], dest=provinces["gas"], army=True, fleet=False),
        Path(origin=provinces["par"], dest=provinces["bre"], army=True, fleet=False),
        Path(origin=provinces["pic"], dest=provinces["eng"], army=False, fleet=True),
        Path(origin=provinces["pic"], dest=provinces["bel"], army=True, fleet=True),
        Path(origin=provinces["pic"], dest=provinces["bur"], army=True, fleet=False),
        Path(origin=provinces["pic"], dest=provinces["bre"], army=True, fleet=True),
        Path(origin=provinces["pic"], dest=provinces["par"], army=True, fleet=False),
        Path(origin=provinces["pie"], dest=provinces["lyo"], army=False, fleet=True),
        Path(origin=provinces["pie"], dest=provinces["ven"], army=True, fleet=False),
        Path(origin=provinces["pie"], dest=provinces["mar"], army=True, fleet=True),
        Path(origin=provinces["pie"], dest=provinces["tyr"], army=True, fleet=False),
        Path(origin=provinces["pie"], dest=provinces["tus"], army=True, fleet=True),
        Path(origin=provinces["por"], dest=provinces["spa_nc"], army=False, fleet=True),
        Path(origin=provinces["por"], dest=provinces["mao"], army=False, fleet=True),
        Path(origin=provinces["por"], dest=provinces["spa"], army=True, fleet=False),
        Path(origin=provinces["por"], dest=provinces["spa_sc"], army=False, fleet=True),
        Path(origin=provinces["pru"], dest=provinces["lvn"], army=True, fleet=True),
        Path(origin=provinces["pru"], dest=provinces["war"], army=True, fleet=False),
        Path(origin=provinces["pru"], dest=provinces["ber"], army=True, fleet=True),
        Path(origin=provinces["pru"], dest=provinces["bal"], army=False, fleet=True),
        Path(origin=provinces["pru"], dest=provinces["sil"], army=True, fleet=False),
        Path(origin=provinces["rom"], dest=provinces["ven"], army=True, fleet=False),
        Path(origin=provinces["rom"], dest=provinces["tus"], army=True, fleet=True),
        Path(origin=provinces["rom"], dest=provinces["tys"], army=False, fleet=True),
        Path(origin=provinces["rom"], dest=provinces["apu"], army=True, fleet=False),
        Path(origin=provinces["rom"], dest=provinces["nap"], army=True, fleet=True),
        Path(origin=provinces["ruh"], dest=provinces["hol"], army=True, fleet=False),
        Path(origin=provinces["ruh"], dest=provinces["mun"], army=True, fleet=False),
        Path(origin=provinces["ruh"], dest=provinces["kie"], army=True, fleet=False),
        Path(origin=provinces["ruh"], dest=provinces["bur"], army=True, fleet=False),
        Path(origin=provinces["ruh"], dest=provinces["bel"], army=True, fleet=False),
        Path(origin=provinces["rum"], dest=provinces["bud"], army=True, fleet=False),
        Path(origin=provinces["rum"], dest=provinces["ukr"], army=True, fleet=False),
        Path(origin=provinces["rum"], dest=provinces["bla"], army=False, fleet=True),
        Path(origin=provinces["rum"], dest=provinces["gal"], army=True, fleet=False),
        Path(origin=provinces["rum"], dest=provinces["ser"], army=True, fleet=False),
        Path(origin=provinces["rum"], dest=provinces["bul"], army=True, fleet=False),
        Path(origin=provinces["rum"], dest=provinces["bul_ec"], army=False, fleet=True),
        Path(origin=provinces["rum"], dest=provinces["sev"], army=True, fleet=True),
        Path(origin=provinces["ser"], dest=provinces["bul"], army=True, fleet=False),
        Path(origin=provinces["ser"], dest=provinces["gre"], army=True, fleet=False),
        Path(origin=provinces["ser"], dest=provinces["tri"], army=True, fleet=False),
        Path(origin=provinces["ser"], dest=provinces["bud"], army=True, fleet=False),
        Path(origin=provinces["ser"], dest=provinces["alb"], army=True, fleet=False),
        Path(origin=provinces["ser"], dest=provinces["rum"], army=True, fleet=False),
        Path(origin=provinces["sev"], dest=provinces["mos"], army=True, fleet=False),
        Path(origin=provinces["sev"], dest=provinces["rum"], army=True, fleet=True),
        Path(origin=provinces["sev"], dest=provinces["bla"], army=False, fleet=True),
        Path(origin=provinces["sev"], dest=provinces["arm"], army=True, fleet=True),
        Path(origin=provinces["sev"], dest=provinces["ukr"], army=True, fleet=False),
        Path(origin=provinces["sil"], dest=provinces["war"], army=True, fleet=False),
        Path(origin=provinces["sil"], dest=provinces["gal"], army=True, fleet=False),
        Path(origin=provinces["sil"], dest=provinces["pru"], army=True, fleet=False),
        Path(origin=provinces["sil"], dest=provinces["mun"], army=True, fleet=False),
        Path(origin=provinces["sil"], dest=provinces["ber"], army=True, fleet=False),
        Path(origin=provinces["sil"], dest=provinces["boh"], army=True, fleet=False),
        Path(origin=provinces["ska"], dest=provinces["nth"], army=False, fleet=True),
        Path(origin=provinces["ska"], dest=provinces["nwy"], army=False, fleet=True),
        Path(origin=provinces["ska"], dest=provinces["swe"], army=False, fleet=True),
        Path(origin=provinces["ska"], dest=provinces["den"], army=False, fleet=True),
        Path(origin=provinces["smy"], dest=provinces["con"], army=True, fleet=True),
        Path(origin=provinces["smy"], dest=provinces["ank"], army=True, fleet=False),
        Path(origin=provinces["smy"], dest=provinces["arm"], army=True, fleet=False),
        Path(origin=provinces["smy"], dest=provinces["syr"], army=True, fleet=True),
        Path(origin=provinces["smy"], dest=provinces["aeg"], army=False, fleet=True),
        Path(origin=provinces["smy"], dest=provinces["eas"], army=False, fleet=True),
        Path(origin=provinces["spa"], dest=provinces["gas"], army=True, fleet=False),
        Path(origin=provinces["spa"], dest=provinces["mar"], army=True, fleet=False),
        Path(origin=provinces["spa"], dest=provinces["por"], army=True, fleet=False),
        Path(origin=provinces["spa_nc"], dest=provinces["gas"], army=False, fleet=True),
        Path(origin=provinces["spa_nc"], dest=provinces["por"], army=False, fleet=True),
        Path(origin=provinces["spa_nc"], dest=provinces["mao"], army=False, fleet=True),
        Path(origin=provinces["spa_sc"], dest=provinces["mar"], army=False, fleet=True),
        Path(origin=provinces["spa_sc"], dest=provinces["mao"], army=False, fleet=True),
        Path(origin=provinces["spa_sc"], dest=provinces["lyo"], army=False, fleet=True),
        Path(origin=provinces["spa_sc"], dest=provinces["wes"], army=False, fleet=True),
        Path(origin=provinces["spa_sc"], dest=provinces["por"], army=False, fleet=True),
        Path(origin=provinces["stp"], dest=provinces["nwy"], army=True, fleet=False),
        Path(origin=provinces["stp"], dest=provinces["fin"], army=True, fleet=False),
        Path(origin=provinces["stp"], dest=provinces["lvn"], army=True, fleet=False),
        Path(origin=provinces["stp"], dest=provinces["mos"], army=True, fleet=False),
        Path(origin=provinces["stp_nc"], dest=provinces["bar"], army=False, fleet=True),
        Path(origin=provinces["stp_nc"], dest=provinces["nwy"], army=False, fleet=True),
        Path(origin=provinces["stp_sc"], dest=provinces["fin"], army=False, fleet=True),
        Path(origin=provinces["stp_sc"], dest=provinces["lvn"], army=False, fleet=True),
        Path(origin=provinces["stp_sc"], dest=provinces["bot"], army=False, fleet=True),
        Path(origin=provinces["swe"], dest=provinces["ska"], army=False, fleet=True),
        Path(origin=provinces["swe"], dest=provinces["den"], army=True, fleet=True),
        Path(origin=provinces["swe"], dest=provinces["nwy"], army=True, fleet=True),
        Path(origin=provinces["swe"], dest=provinces["fin"], army=True, fleet=True),
        Path(origin=provinces["swe"], dest=provinces["bot"], army=False, fleet=True),
        Path(origin=provinces["swe"], dest=provinces["bal"], army=False, fleet=True),
        Path(origin=provinces["syr"], dest=provinces["arm"], army=True, fleet=False),
        Path(origin=provinces["syr"], dest=provinces["eas"], army=False, fleet=True),
        Path(origin=provinces["syr"], dest=provinces["smy"], army=True, fleet=True),
        Path(origin=provinces["tri"], dest=provinces["vie"], army=True, fleet=False),
        Path(origin=provinces["tri"], dest=provinces["alb"], army=True, fleet=True),
        Path(origin=provinces["tri"], dest=provinces["adr"], army=False, fleet=True),
        Path(origin=provinces["tri"], dest=provinces["ven"], army=True, fleet=True),
        Path(origin=provinces["tri"], dest=provinces["ser"], army=True, fleet=False),
        Path(origin=provinces["tri"], dest=provinces["tyr"], army=True, fleet=False),
        Path(origin=provinces["tri"], dest=provinces["bud"], army=True, fleet=False),
        Path(origin=provinces["tun"], dest=provinces["wes"], army=False, fleet=True),
        Path(origin=provinces["tun"], dest=provinces["tys"], army=False, fleet=True),
        Path(origin=provinces["tun"], dest=provinces["ion"], army=False, fleet=True),
        Path(origin=provinces["tun"], dest=provinces["naf"], army=True, fleet=True),
        Path(origin=provinces["tus"], dest=provinces["lyo"], army=False, fleet=True),
        Path(origin=provinces["tus"], dest=provinces["ven"], army=True, fleet=False),
        Path(origin=provinces["tus"], dest=provinces["tys"], army=False, fleet=True),
        Path(origin=provinces["tus"], dest=provinces["pie"], army=True, fleet=True),
        Path(origin=provinces["tus"], dest=provinces["rom"], army=True, fleet=True),
        Path(origin=provinces["tyr"], dest=provinces["vie"], army=True, fleet=False),
        Path(origin=provinces["tyr"], dest=provinces["tri"], army=True, fleet=False),
        Path(origin=provinces["tyr"], dest=provinces["mun"], army=True, fleet=False),
        Path(origin=provinces["tyr"], dest=provinces["boh"], army=True, fleet=False),
        Path(origin=provinces["tyr"], dest=provinces["ven"], army=True, fleet=False),
        Path(origin=provinces["tyr"], dest=provinces["pie"], army=True, fleet=False),
        Path(origin=provinces["tys"], dest=provinces["tus"], army=False, fleet=True),
        Path(origin=provinces["tys"], dest=provinces["ion"], army=False, fleet=True),
        Path(origin=provinces["tys"], dest=provinces["rom"], army=False, fleet=True),
        Path(origin=provinces["tys"], dest=provinces["tun"], army=False, fleet=True),
        Path(origin=provinces["tys"], dest=provinces["wes"], army=False, fleet=True),
        Path(origin=provinces["tys"], dest=provinces["lyo"], army=False, fleet=True),
        Path(origin=provinces["tys"], dest=provinces["nap"], army=False, fleet=True),
        Path(origin=provinces["ukr"], dest=provinces["sev"], army=True, fleet=False),
        Path(origin=provinces["ukr"], dest=provinces["mos"], army=True, fleet=False),
        Path(origin=provinces["ukr"], dest=provinces["rum"], army=True, fleet=False),
        Path(origin=provinces["ukr"], dest=provinces["gal"], army=True, fleet=False),
        Path(origin=provinces["ukr"], dest=provinces["war"], army=True, fleet=False),
        Path(origin=provinces["ven"], dest=provinces["tri"], army=True, fleet=True),
        Path(origin=provinces["ven"], dest=provinces["adr"], army=False, fleet=True),
        Path(origin=provinces["ven"], dest=provinces["apu"], army=True, fleet=True),
        Path(origin=provinces["ven"], dest=provinces["tyr"], army=True, fleet=False),
        Path(origin=provinces["ven"], dest=provinces["pie"], army=True, fleet=False),
        Path(origin=provinces["ven"], dest=provinces["rom"], army=True, fleet=False),
        Path(origin=provinces["ven"], dest=provinces["tus"], army=True, fleet=False),
        Path(origin=provinces["vie"], dest=provinces["gal"], army=True, fleet=False),
        Path(origin=provinces["vie"], dest=provinces["tyr"], army=True, fleet=False),
        Path(origin=provinces["vie"], dest=provinces["tri"], army=True, fleet=False),
        Path(origin=provinces["vie"], dest=provinces["boh"], army=True, fleet=False),
        Path(origin=provinces["vie"], dest=provinces["bud"], army=True, fleet=False),
        Path(origin=provinces["wal"], dest=provinces["eng"], army=False, fleet=True),
        Path(origin=provinces["wal"], dest=provinces["lvp"], army=True, fleet=True),
        Path(origin=provinces["wal"], dest=provinces["iri"], army=False, fleet=True),
        Path(origin=provinces["wal"], dest=provinces["lon"], army=True, fleet=True),
        Path(origin=provinces["wal"], dest=provinces["yor"], army=True, fleet=False),
        Path(origin=provinces["war"], dest=provinces["ukr"], army=True, fleet=False),
        Path(origin=provinces["war"], dest=provinces["pru"], army=True, fleet=False),
        Path(origin=provinces["war"], dest=provinces["gal"], army=True, fleet=False),
        Path(origin=provinces["war"], dest=provinces["mos"], army=True, fleet=False),
        Path(origin=provinces["war"], dest=provinces["sil"], army=True, fleet=False),
        Path(origin=provinces["war"], dest=provinces["lvn"], army=True, fleet=False),
        Path(origin=provinces["wes"], dest=provinces["tys"], army=False, fleet=True),
        Path(origin=provinces["wes"], dest=provinces["mao"], army=False, fleet=True),
        Path(origin=provinces["wes"], dest=provinces["tun"], army=False, fleet=True),
        Path(origin=provinces["wes"], dest=provinces["spa_sc"], army=False, fleet=True),
        Path(origin=provinces["wes"], dest=provinces["naf"], army=False, fleet=True),
        Path(origin=provinces["wes"], dest=provinces["lyo"], army=False, fleet=True),
        Path(origin=provinces["yor"], dest=provinces["edi"], army=True, fleet=True),
        Path(origin=provinces["yor"], dest=provinces["wal"], army=True, fleet=False),
        Path(origin=provinces["yor"], dest=provinces["lon"], army=True, fleet=True),
        Path(origin=provinces["yor"], dest=provinces["nth"], army=False, fleet=True),
        Path(origin=provinces["yor"], dest=provinces["lvp"], army=True, fleet=False),
    ]
    db.add_all(paths)
    await db.commit()
