@startuml seq_login
title login

actor User
Participant frontend as FE
Participant backend as BE
Participant database as DB
Participant provider as OP

User -> FE : login operation
    FE -> OP : oauth request
        OP -> User : show auth page
        User -> OP : accept operation
    OP -> FE : provider api access token
    FE -> BE : provider api access token
        BE -> OP : provider api access token
        OP -> BE : user data
        BE -> DB : query user data
== first login ==
        DB -> BE : "not found"
        BE -> BE : create user data
            note right
                generate server access key
            end note
        BE -> DB : store user data
        DB -> BE :
== subsequent login ==
        DB -> BE : user data
        BE -> BE : update user data
        BE -> DB : update user data
        DB -> BE :
== ==
    BE -> FE : server access key
    FE -> FE : store server access key
FE -> User : logged in

@enduml
